/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface BlogPost {
  'id' : bigint,
  'title' : string,
  'content' : string,
  'slug' : string,
  'tags' : Array<string>,
  'author' : string,
  'is_published' : boolean,
  'excerpt' : string,
  'category' : string,
  'published_date' : Time,
}
export type Time = bigint;
export interface Vehicle {
  'id' : bigint,
  'top_speed' : bigint,
  'brakes' : string,
  'charging_hours' : number,
  'name' : string,
  'description' : string,
  'is_featured' : boolean,
  'battery_kwh' : number,
  'category' : string,
  'suspension' : string,
  'brand' : string,
  'range_km' : bigint,
  'price_max' : bigint,
  'price_min' : bigint,
  'warranty' : string,
  'motor_watts' : bigint,
}
export interface _SERVICE {
  'addAppointmentBooking' : ActorMethod<
    [string, string, string, string, string, string, string],
    undefined
  >,
  'addContactSubmission' : ActorMethod<
    [string, string, string, string],
    undefined
  >,
  'addFranchiseApplication' : ActorMethod<
    [string, string, string, string, string, bigint, string],
    undefined
  >,
  'addNewsletterSubscriber' : ActorMethod<[string], undefined>,
  'addQuoteRequest' : ActorMethod<
    [string, string, string, string, string],
    undefined
  >,
  'addVehicleEnquiry' : ActorMethod<
    [bigint, string, string, string, string, string],
    undefined
  >,
  'getAllPublishedBlogPosts' : ActorMethod<[], Array<BlogPost>>,
  'getAllVehicles' : ActorMethod<[], Array<Vehicle>>,
  'getBlogPostBySlug' : ActorMethod<[string], BlogPost>,
  'getFeaturedVehicles' : ActorMethod<[], Array<Vehicle>>,
  'getVehicleById' : ActorMethod<[bigint], Vehicle>,
  'getVehiclesByCategory' : ActorMethod<[string], Array<Vehicle>>,
  'seedData' : ActorMethod<[], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];