/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const Time = IDL.Int;
export const BlogPost = IDL.Record({
  'id' : IDL.Nat,
  'title' : IDL.Text,
  'content' : IDL.Text,
  'slug' : IDL.Text,
  'tags' : IDL.Vec(IDL.Text),
  'author' : IDL.Text,
  'is_published' : IDL.Bool,
  'excerpt' : IDL.Text,
  'category' : IDL.Text,
  'published_date' : Time,
});
export const Vehicle = IDL.Record({
  'id' : IDL.Nat,
  'top_speed' : IDL.Nat,
  'brakes' : IDL.Text,
  'charging_hours' : IDL.Float64,
  'name' : IDL.Text,
  'description' : IDL.Text,
  'is_featured' : IDL.Bool,
  'battery_kwh' : IDL.Float64,
  'category' : IDL.Text,
  'suspension' : IDL.Text,
  'brand' : IDL.Text,
  'range_km' : IDL.Nat,
  'price_max' : IDL.Nat,
  'price_min' : IDL.Nat,
  'warranty' : IDL.Text,
  'motor_watts' : IDL.Nat,
});

export const idlService = IDL.Service({
  'addAppointmentBooking' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Text],
      [],
      [],
    ),
  'addCallbackRequest' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text, IDL.Text],
      [],
      [],
    ),
  'addContactSubmission' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text, IDL.Text],
      [],
      [],
    ),
  'addConversionInquiry' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Text],
      [],
      [],
    ),
  'addFranchiseApplication' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Nat, IDL.Text],
      [],
      [],
    ),
  'addNewsletterSubscriber' : IDL.Func([IDL.Text], [], []),
  'addQuoteRequest' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Text],
      [],
      [],
    ),
  'addVehicleEnquiry' : IDL.Func(
      [IDL.Nat, IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Text],
      [],
      [],
    ),
  'getAllPublishedBlogPosts' : IDL.Func([], [IDL.Vec(BlogPost)], ['query']),
  'getAllVehicles' : IDL.Func([], [IDL.Vec(Vehicle)], ['query']),
  'getBlogPostBySlug' : IDL.Func([IDL.Text], [BlogPost], ['query']),
  'getFeaturedVehicles' : IDL.Func([], [IDL.Vec(Vehicle)], ['query']),
  'getVehicleById' : IDL.Func([IDL.Nat], [Vehicle], ['query']),
  'getVehiclesByCategory' : IDL.Func([IDL.Text], [IDL.Vec(Vehicle)], ['query']),
  'seedData' : IDL.Func([], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const Time = IDL.Int;
  const BlogPost = IDL.Record({
    'id' : IDL.Nat,
    'title' : IDL.Text,
    'content' : IDL.Text,
    'slug' : IDL.Text,
    'tags' : IDL.Vec(IDL.Text),
    'author' : IDL.Text,
    'is_published' : IDL.Bool,
    'excerpt' : IDL.Text,
    'category' : IDL.Text,
    'published_date' : Time,
  });
  const Vehicle = IDL.Record({
    'id' : IDL.Nat,
    'top_speed' : IDL.Nat,
    'brakes' : IDL.Text,
    'charging_hours' : IDL.Float64,
    'name' : IDL.Text,
    'description' : IDL.Text,
    'is_featured' : IDL.Bool,
    'battery_kwh' : IDL.Float64,
    'category' : IDL.Text,
    'suspension' : IDL.Text,
    'brand' : IDL.Text,
    'range_km' : IDL.Nat,
    'price_max' : IDL.Nat,
    'price_min' : IDL.Nat,
    'warranty' : IDL.Text,
    'motor_watts' : IDL.Nat,
  });
  
  return IDL.Service({
    'addAppointmentBooking' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Text],
        [],
        [],
      ),
    'addCallbackRequest' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text, IDL.Text],
        [],
        [],
      ),
    'addContactSubmission' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text, IDL.Text],
        [],
        [],
      ),
    'addConversionInquiry' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Text],
        [],
        [],
      ),
    'addFranchiseApplication' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Nat, IDL.Text],
        [],
        [],
      ),
    'addNewsletterSubscriber' : IDL.Func([IDL.Text], [], []),
    'addQuoteRequest' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Text],
        [],
        [],
      ),
    'addVehicleEnquiry' : IDL.Func(
        [IDL.Nat, IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Text],
        [],
        [],
      ),
    'getAllPublishedBlogPosts' : IDL.Func([], [IDL.Vec(BlogPost)], ['query']),
    'getAllVehicles' : IDL.Func([], [IDL.Vec(Vehicle)], ['query']),
    'getBlogPostBySlug' : IDL.Func([IDL.Text], [BlogPost], ['query']),
    'getFeaturedVehicles' : IDL.Func([], [IDL.Vec(Vehicle)], ['query']),
    'getVehicleById' : IDL.Func([IDL.Nat], [Vehicle], ['query']),
    'getVehiclesByCategory' : IDL.Func(
        [IDL.Text],
        [IDL.Vec(Vehicle)],
        ['query'],
      ),
    'seedData' : IDL.Func([], [], []),
  });
};

export const init = ({ IDL }) => { return []; };